
version: '3.1'

services:

  nginx:
    image: rodezee/${PROJECT_NAME}:${VERSION}
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      NGINX_HOST: foobar.com
      NGINX_PORT: 80

